# Numpy - Python

Library for scientific computing, that provides multidimensional array abject, routines for fast operations on arrays, whethher mathematical, logical, shape, manipulation, sorting, selecting, I/O, basic linear algebra, basic statistical operations, etc.

The core of the Numpy package is the *ndarray* that encapsulates n-dimensional arrays.

[Reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html)


## Introduction to data structures

### Table of Content
* 1 - Array
  * 1.1 - Array Atributes
  * 1.2 - Array attributes
    * 1.2.1 - Set dimensionality
      * 1.2.1.1 - 1D array
      * 1.2.1.2 - 2D array
      * 1.2.1.3 - 3D array
    * 1.2.2 - Basic operations



# 1 - Array

Is the central data structure of the NumPy library.

In [1]:
import numpy as np

Below formula `.arange(12)` specifies the creation of an array with range 12, with numbers going from 0 to 11. The `.reshap` function specifies the number of rows and columns for the array.

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 1.1 - Array attributes

The most important *ndarray* atributes are:

|Function     |Description    |
|-------------|---------------|
|.ndim        |Number of axes (dimensionality)|
|.shape       |size o array in each dimension|
|.size        |number of elements|
|.dtype       |type of elements|
|.itemsize    |size in bites|

In [3]:
a.ndim

2

In [4]:
a.shape

(3, 4)

In [5]:
a.size

12

In [6]:
a.dtype

dtype('int32')

## 1.2 - Array creation

Can be created from a regular Python list or tuple using `array` function

In [7]:
x = np.array([1, 3, 5])
x

array([1, 3, 5])

In [8]:
y = np.array([(1.5, 2, 4),
              (4,   5, 6)
             ])
y

array([[1.5, 2. , 4. ],
       [4. , 5. , 6. ]])

### 1.2.1 - Set dimensionality
#### 1.2.1.1 - 1D array

In [9]:
print(np.arange(6))

[0 1 2 3 4 5]


#### 1.2.1.2 - 2D array

In [10]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 1.2.1.3 - 3D array

In [11]:
print(np.arange(24).reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 1.2.2 - Basic operations

#### 1.2.2.1 - Operations between Matrices

In [12]:
arr = np.array([[1, 2, 3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr * arr


array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [17]:
arr ** 2    # ** to the power 

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [18]:
arr2 = np.array([[0,4,1], [7,8,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  8, 12]])

In [22]:
arr2 > arr

array([[False,  True, False],
       [ True,  True,  True]])

#### 1.2.2.2 - Unari operations

In [23]:
arr.sum()

21

In [24]:
arr.min()

1

In [25]:
arr.max()

6