# Numpy - Python

[Reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

### Table of Content
* 1 - Boolean Indexing
  * 1.1 - Selection
    * 1.1.1 - Positive Condition
    * 1.1.2 - Negative Condition
     * 1.1.2.1 - Except Condition
     * 1.1.2.2 - Negate Condition
   * 1.1.3 - Multiple Boolean Conditions


# 1 - Boolean Indexing

Below it will be created two objects, that refer to a series of entries for 4 funds with negative and positive positions. The first object is a 1D array with the funds, the second object is a 2D array with the corresponding NPV and market value.

In [1]:
import numpy as np

In [2]:
Funds = np.array(['Fund A', 'Fund B', 'Fund C', 'Fund A', 'Fund C', 'Fund B', 'Fund B'])
Values = np.array([[254.5, 254.2], 
                   [-235.9, -236.1],
                   [619.96, 621.2], 
                   [123.9, 123.9],
                   [-249.56, -248.78],
                   [197.8, 197.8],
                   [246.5, 246.5]
                  ])
Funds

array(['Fund A', 'Fund B', 'Fund C', 'Fund A', 'Fund C', 'Fund B',
       'Fund B'], dtype='<U6')

In [3]:
Values

array([[ 254.5 ,  254.2 ],
       [-235.9 , -236.1 ],
       [ 619.96,  621.2 ],
       [ 123.9 ,  123.9 ],
       [-249.56, -248.78],
       [ 197.8 ,  197.8 ],
       [ 246.5 ,  246.5 ]])

## 1.1 - Selection

### 1.1.1 - Positive Condition
Apply a filter only to the `Fund C` from `Funds` array for this puspose use the condition `== 'Fund B'`. This will return an array with `True` and `False`. This is a *Boolean*.

In [4]:
Funds == 'Fund C'

array([False, False,  True, False,  True, False, False])

##### Indexing the Boolean
Apply the *boolean* results to the NPV and Market Value table. **Note:** The boolean indexing must be of the same length as the axis that is being indexed

In [5]:
Values[Funds == 'Fund C']

array([[ 619.96,  621.2 ],
       [-249.56, -248.78]])

### 1.1.2 - Negative condition
To select all Funds except for `Fund C` one can use either `!= 'Fund C'` or the negate condition `~`
#### 1.1.2.1 - Except Condition

In [6]:
Funds != 'Fund C'

array([ True,  True, False,  True, False,  True,  True])

In [7]:
Values[Funds != 'Fund C']

array([[ 254.5,  254.2],
       [-235.9, -236.1],
       [ 123.9,  123.9],
       [ 197.8,  197.8],
       [ 246.5,  246.5]])

#### 1.1.2.2 - Negate Condition
Negate condition is an alternative way to achieve the result presented above.

In [8]:
Values[~(Funds == 'Fund C')]

array([[ 254.5,  254.2],
       [-235.9, -236.1],
       [ 123.9,  123.9],
       [ 197.8,  197.8],
       [ 246.5,  246.5]])

### 1.1.3 - Multiple boolean conditions
Use arithmetic operators like & (and) and | (or). Below example shows condition for `Fund A` or `Fund B`.

In [9]:
(Funds == 'Fund A') | (Funds == 'Fund B')

array([ True,  True, False,  True, False,  True,  True])

In [10]:
mask = (Funds == 'Fund A') | (Funds == 'Fund B')
mask

array([ True,  True, False,  True, False,  True,  True])

In [11]:
Funds[mask] 

array(['Fund A', 'Fund B', 'Fund A', 'Fund B', 'Fund B'], dtype='<U6')

In [12]:
Values[mask]

array([[ 254.5,  254.2],
       [-235.9, -236.1],
       [ 123.9,  123.9],
       [ 197.8,  197.8],
       [ 246.5,  246.5]])