# Numpy - Python

[Reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

### Table of Content
* 1 - Universal Functions
  * 1.1 - Unary functions
  * 1.2 - Binay functions
 

# 1 - Universal Functions
Function that performs elementwise operations on data in ndarrays.

## 1.1 - Unary Functions  

| Function        | Description |
|-----------------|-------------|
|abs, fabs        | Compute the absolute value |
|sqrt             | Compute the square root (equivalent to arr ** 0.5) |
|square           | Compute the square (equivalent to arr ** 2) |
|exp              | Compute the exponent ( e ** x) |
|log, log10, log2 | Natural logarithm (basee , 10, 2) |


In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## 1.2 - Binary Functions

| Function        | Description |
|-----------------|-------------|
|add              | Add corresponding elements in array |
|subtract         | Subtract elements in second array from first array |
|multiply         | multiply array elements |
|divide (divide_floor)| divide o floor divide |
|power            | raise elements in first array to power |
|greater, greater_equal, less, less_equal, equal, not_equal| equivalent (>, >=, <, <=, ==, !=) |

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)

In [5]:
x

array([-2.81845527,  1.19795062,  0.74989907,  0.98479261,  0.86988229,
        0.37968988,  0.63712935,  0.55023093])

In [6]:
y

array([-1.88624661,  2.37696088,  0.97502058,  0.83859765,  1.27060325,
       -1.26397923,  1.44894978,  1.50820073])

In [7]:
np.maximum(x, y)

array([-1.88624661,  2.37696088,  0.97502058,  0.98479261,  1.27060325,
        0.37968988,  1.44894978,  1.50820073])

In [9]:
np.greater(x, y)

array([False, False, False,  True, False,  True, False, False])

**Bonus**

In [10]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
a

array([[-2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

In [11]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """
c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """
