# Numpy - Python

[Reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

### Table of Content
* 1 - Array Oriented Programming
  * 1.1 - Conditional Logic
  * 1.2 - Mathematical and Statistical Methods
    * 1.2.1 - `ndarray` methods
      * 1.2.1.1 - Apply function to entire matrix
      * 1.2.1.2 - Apply functions across rows and columns
    * 1.2.2 - Methods for Boolean arrays
  * 1.3 - Sorting
  
# 1 - Array Oriented Programming
## 1.1 - Conditional Logic

Numpy allows to use the `.where()` function to perform a `if..., then...!` type of statement. As example `np.where(cond, x, y)` states that if condition is satisfied, output is x, if not output is why.

In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [3]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [4]:
arr = np.random.randn(4,4)
arr

array([[-0.22905164, -0.66881094,  0.45308155,  0.88401236],
       [-0.88733109,  0.37460166,  1.14092322,  0.986086  ],
       [-1.77654378,  0.06509913, -0.59691448,  0.52400794],
       [-2.03245556, -0.29303193,  0.46272473, -1.97647042]])

In [5]:
np.where(arr > 0, 2, 1)

array([[1, 1, 2, 2],
       [1, 2, 2, 2],
       [1, 2, 1, 2],
       [1, 1, 2, 1]])

## 1.2 - Mathematical and Statistical Methods
### 1.2.1 - `ndarray` methods
#### 1.2.1.1 - Apply function to the entire matrix

In [6]:
arr.mean()

-0.22312957813884537

In [7]:
for func in (arr.min, arr.max, arr.sum, arr.prod, arr.std, arr.var):
    print(func.__name__, "=", func())

min = -2.03245555874778
max = 1.1409232224052936
sum = -3.570073250221526
prod = 0.0004521142988343273
std = 1.0006319420061127
var = 1.0012642833629246


### 1.2.1.2 - Apply functions across rows and columns

#### Across rows

In [8]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
c.sum(axis=0)

array([12, 15, 18, 21])

#### Across Columns

In [10]:
c.sum(axis=1)

array([ 6, 22, 38])

In [11]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [12]:
d.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

### 1.2.2 - Methods for boolean arrays
Count the number of positive values

In [13]:
(arr > 0).sum()

8

### 1.3 - Sorting
`.sort()` will apply sorting allong along columns

In [14]:
arr.sort()
arr

array([[-0.66881094, -0.22905164,  0.45308155,  0.88401236],
       [-0.88733109,  0.37460166,  0.986086  ,  1.14092322],
       [-1.77654378, -0.59691448,  0.06509913,  0.52400794],
       [-2.03245556, -1.97647042, -0.29303193,  0.46272473]])

`.sort(0)` will apply sorting allong along rows

In [15]:
arr.sort(0)
arr

array([[-2.03245556, -1.97647042, -0.29303193,  0.46272473],
       [-1.77654378, -0.59691448,  0.06509913,  0.52400794],
       [-0.88733109, -0.22905164,  0.45308155,  0.88401236],
       [-0.66881094,  0.37460166,  0.986086  ,  1.14092322]])