# Numpy - Python

[Reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

### Table of Content
* 1 - Stacking Arrays
  * 1.1 - Vertical Stacking `vstack`
  * 1.2 - Horizontal Stacking `hstack`
  * 1.3 - Concatenate
  * 1.4 - Stack
* 2 - Splitting
  * 2.1 - Vertical Splitting `vsplit`
  * 2.1 - Horizontal Splitting `hsplit`
  
  
# 1 - Stacking Arrays
Stack together different arrays, simular o append, join, merge and concatenate from pandas

## 1.1 - Vertical Stacking `vstack`

In [1]:
import numpy as np

In [2]:
q1 = np.full((2, 3), 1)
q1

array([[1, 1, 1],
       [1, 1, 1]])

In [3]:
q2 = np.full((2, 3), 2)
q2

array([[2, 2, 2],
       [2, 2, 2]])

In [4]:
q3 = np.full((2, 3), 3)
q3

array([[3, 3, 3],
       [3, 3, 3]])

`vstack`

In [6]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3]])

## 1.2 - Horizontal Stacking `hstack`

In [7]:
q5 = np.hstack((q1, q2, q3))
q5

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

## 1.3 - Concatenate

In [8]:
#q6 = np.concatenate((q1, q2, q3), axis = 0)  Equivalent to vstack
q6 = np.concatenate((q1, q2, q3))
q6

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3]])

In [9]:
q7 = np.concatenate((q1, q2, q3), axis = 1)  #Equivalent to hstack
q7

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

## 1.4 - Stack

`Stack` function stacks arrays along a new axis

In [10]:
q8 = np.stack((q1, q3))
q8

array([[[1, 1, 1],
        [1, 1, 1]],

       [[3, 3, 3],
        [3, 3, 3]]])

# 2 - Splitting

In [16]:
Funds = np.array(['Fund A', 'Fund A', 'Fund A', 'Fund B', 'Fund B', 'Fund B', 'Fund C', 'Fund C', 'Fund C'])
Funds

array(['Fund A', 'Fund A', 'Fund A', 'Fund B', 'Fund B', 'Fund B',
       'Fund C', 'Fund C', 'Fund C'], dtype='<U6')

In [17]:
np.split(Funds, 3)

[array(['Fund A', 'Fund A', 'Fund A'], dtype='<U6'),
 array(['Fund B', 'Fund B', 'Fund B'], dtype='<U6'),
 array(['Fund C', 'Fund C', 'Fund C'], dtype='<U6')]

In [18]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 2.1 - Vertical Splitting `vsplit`

In [19]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 2.2 - Horizontal Splitting `hsplit`

In [21]:
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [22]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])